config/routes.rb
Rails.application.routes.draw do
  
  resources :listings



  devise_for :users
  get 'pages/index'
root :to => "pages#index"

get 'manage-listing/:id/basics' => 'listings#basics', as: 'manage_listing_basics'

get '/search' => 'pages#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user

  #必須項目
  validates :company, presence: true

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :listings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!

  def index
    @listings = current_user.listings
  end

  def show
    @listing = Listing.find(params[:id])

  end

  def new

    @listing = current_user.listings.build
  end

  def create
    #パラメータとともに作成
      @listing = current_user.listings.build(listing_params)
  if @listing.save
    redirect_to manage_listing_basics_path(@listing), notice: "作成保存完了"
  else
    redirect_to manage_listing_basics_path(@listing), notice: "作成保存失敗"
  end
  end

  def edit
  end

  def update
    @listing = Listing.find(params[:id])
    @listing.update(listing_params)
    redirect_to :back, notice: "更新完了"
  end

  def basics
    @listing = Listing.find(params[:id])
  end

  private
  def listing_params
    params.require(:listing).permit(:company,:kigyoutantou,:address,:tel,:comment)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index #views/index.html.erbを表示させるというアクション
    @users = User.all
  end

  def search
    if params[:search].present?

      @latitude = params["lat"]
      @longitude = params["lng"]

      geolocation = [@latitude,@longitude]

      @listings = Listing.near([@latitude,@longitude], 1, order: 'distance')
    # 検索欄が空欄の場合
    else


      @latitude = @listings.to_a[0].latitude
      @longitude = @listings.to_a[0].longitude

    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aprec</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>


  </body>
</html>

app/views/listings/basics.html.erb
<%= render 'navbar/navbar' %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="text-center">
            <span style="font-size:24px;">企業情報</span>
          </div>
        </div>
      
        <div class="panel-body">      
          <!-- ここからフォーム -->
          <%= form_for @listing do |f| %>
            <div class="row">
              <div class="col-md-12 select">
                <div class="form-group">
                  <label>会社名</label>
                  <%= f.text_field :company, {required: 'true', autofocus: 'true', class: 'form-control'} %>
                </div>
              </div>
            </div>
            <br>
            <div class="row">
              <div class="col-md-12 select">
                <div class="form-group">
                  <label>住所</label>
                  <%= f.text_field :address, {autofocus: 'true', class: 'form-control'} %>
                </div>
              </div>
            </div>
            <br>
            <div class="row">
              <div class="col-md-12 select">
                <div class="form-group">
                  <label>電話番号</label>
                  <%= f.text_field :tel, {autofocus: 'true', class: 'form-control'} %>
                </div>
              </div>
            </div>
            <br>
            <div class="row">
              <div class="col-md-12 select">
                <div class="form-group">
                  <label>担当</label>
                  <%= f.text_field :kigyoutantou, { autofocus: 'true', class: 'form-control'} %>
                </div>
              </div>
            </div>
            <br>
            <div class="row">
              <div class="col-md-12 select">
                <div class="form-group">
                  <label>コメント</label>
                  <%= f.text_field :comment, {autofocus: 'true', class: 'form-control'} %>
                </div>
              </div>
            </div>
            <br>
            <div class="actions">
              <%= f.submit "更新", class: "btn btn-danger" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/listings/create.html.erb
<h1>Listings#create</h1>
<p>Find me in app/views/listings/create.html.erb</p>

app/views/listings/edit.html.erb
<h1>Listings#edit</h1>
<p>Find me in app/views/listings/edit.html.erb</p>

app/views/listings/index.html.erb
<%= render 'navbar/navbar' %>

<div class="container"> 
    <div class="col-md-10 col-md-offset-1">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="text-center">
                    <span style="font-size:18px;">一覧</span>
                </div>
            </div>
            <ul class="ul-unstyled">
                <% @listings.each do |listing| %>
                    <li class="panel-body">
                        <div class="row-table">

                            <div class="col-sm-7 col-lg-7 col-middle row-space-2">
                                <span class="listing-title"><%= listing.company %>,<%= listing.tel %>,<%= listing.kigyoutantou %><%= listing.comment %></span>
                            </div>
                            
                            <div class="col-md-3 col-sm-3 col-middle row-space-1">
                                <%= link_to "企業情報", manage_listing_basics_path(listing), class: "btn btn-primary pull-right" %>
                            </div>
                        </div>
                    </li>
                <% end %>               
            </ul>     
        </div>
        
    </div>
</div>

app/views/listings/new.html.erb
<%= render 'navbar/navbar' %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="text-center">
            <span style="font-size:24px;">企業情報</span>
          </div>
        </div>
      
        <div class="panel-body">      
          <!-- ここからフォーム -->
          <%= form_for @listing do |f| %>
            <div class="row">
              <div class="col-md-12 select">
                <div class="form-group">
                  <label>会社名</label>
                  <%= f.text_field :company, {required: 'true', autofocus: 'true', class: 'form-control'} %>
                </div>
              </div>
            </div>
            <br>
            <div class="row">
              <div class="col-md-12 select">
                <div class="form-group">
                  <label>住所</label>
                  <%= f.text_field :address, {autofocus: 'true', class: 'form-control'} %>
                </div>
              </div>
            </div>
            <br>
            <div class="row">
              <div class="col-md-12 select">
                <div class="form-group">
                  <label>電話番号</label>
                  <%= f.text_field :tel, {autofocus: 'true', class: 'form-control'} %>
                </div>
              </div>
            </div>
            <br>
            <div class="row">
              <div class="col-md-12 select">
                <div class="form-group">
                  <label>担当</label>
                  <%= f.text_field :kigyoutantou, { autofocus: 'true', class: 'form-control'} %>
                </div>
              </div>
            </div>
            <br>
            <div class="row">
              <div class="col-md-12 select">
                <div class="form-group">
                  <label>コメント欄</label>
                  <%= f.text_field :comment, {autofocus: 'true', class: 'form-control'} %>
                </div>
              </div>
            </div>
            <br>
            <div class="actions">
              <%= f.submit "Save", class: "btn btn-danger" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/listings/show.html.erb
<%= render 'navbar/navbar' %>

<!-- サマリー -->
<div class="page-header">
  <h1> <%= @listing.company %> <small>tel:<%= @listing.tel %></small></h1>
</div>
<ul class="list-group">
  <li class="list-group-item"><%= @listing.address %></li>
  <li class="list-group-item"><%= @listing.kigyoutantou %></li>
  <li class="list-group-item"><%= @listing.comment %></li>

</ul>



    <!-- google map    -->
    <div class="row">
        <div class="col-md-9">
            <h3 class="row-space-3">アクセス</h3>
            <div id="map"></div>
        </div>

        <div class="col-md-3">
        
        </div>
    </div>
    <style>
        #map{
            width: 100%;
            height: 350px;
        }
    </style>
<div class="row">
   <div class="col-md-9">
      <h3 class="row-space-3">近くの会社</h3>
     <% for listing in @listing.nearbys(1) %>
      <div class="col-md-3">
         <div class="panel panel-default">
            <div class="panel-heading panel-listing text-center" style="padding: 0;">
               <%= link_to(listing) do %>

               <% end %>
           </div>

           <div class="panel-body">
               <div class="row">
                  <div class="col-md-9 col-xs-8">
                     <%= link_to listing.company, listing %><br>
                 </div>
                 <div class="col-md-3 col-xs-3">
                 </div>
                 <div class="price-card">
                     tel:<%= listing.tel %> 
                 </div>
               </div>
             </div>
           </div>
         </div>
       <% end %>
     </div>
     <div class="col-md-3">
   </div>
</div>
   <script>



function initMap() {
  // Create the map.
var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 14,
    center: {lat: <%= @listing.latitude %>, lng:<%= @listing.longitude %>},
    mapTypeId: google.maps.MapTypeId.TERRAIN
});
  // Construct the circle for each value in citymap.
  // Note: We scale the area of the circle based on the population.

    // Add the circle for this city to the map.

    var cityCircle = new google.maps.Circle({
    strokeColor: '#FF0000',
    strokeOpacity: 0.8,
    strokeWeight: 2,
    fillColor: '#FF0000',
    fillOpacity: 0.35,
    map: map,
    center: {lat: <%= @listing.latitude %>, lng:<%= @listing.longitude %>},
    radius: 800
});

 var marker = new google.maps.Marker({
    position: {lat: <%= @listing.latitude %>, lng:<%= @listing.longitude %>},
    map: map,
    title: "<%= @listing.company %>、<%= @listing.tel %>"
  });
}

    </script>

        <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA_cz1s18wSQrIRmZ7aAu9W4IpvzhKXaOc&callback=initMap"></script>

app/views/listings/update.html.erb
<h1>Listings#update</h1>
<p>Find me in app/views/listings/update.html.erb</p>

app/views/navbar/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">ホーム</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "アカウント作成",new_user_registration_path %></li>
        <li><%= link_to "ログイン ",new_user_session_path %></li>
        <li><%= link_to "ログアウト ",destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "情報追加",new_listing_path %></li>
        <li><%= link_to "情報",listings_path  %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/pages/index.html.erb
<%= render 'navbar/navbar'%>
  <!-- Search Form -->
  <div class="top-search-field">
    <%= form_tag search_path, method: :get do %>
      <div class="row">
        <div class="container">
          
          <%= hidden_field_tag :lat %>
          <%= hidden_field_tag :lng %>

          <div class="col-md-7 col-xs-10" style="padding-right: 0px">
            <%= text_field_tag :search, params[:search], placeholder: "場所検索", class: "form-control",id:"top-search-form" %>
          </div>

       
          <div class="col-md-1 col-xs-2" style="padding-left: 0px; ">
            <%= submit_tag "検索", class: "btn btn-danger" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>





        <script>
function init() {

  var input = /** @type {!HTMLInputElement} */(
      document.getElementById('top-search-form'));

  var autocomplete = new google.maps.places.Autocomplete(input);



  autocomplete.addListener('place_changed', function() {
    var place = autocomplete.getPlace();
    var lat = place.geometry.location.lat();
    var lng = place.geometry.location.lng();

    document.getElementById('lat').value = lat;
    document.getElementById('lng').value = lng;


    alert(lat);


    if (!place.geometry) {
      window.alert("Autocomplete's returned place contains no geometry");
      return;
    }


});

}

    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA_cz1s18wSQrIRmZ7aAu9W4IpvzhKXaOc&libraries=places&callback=init"
        async defer></script>

app/views/pages/search.html.erb
<%= render 'navbar/navbar'%>
<div class="col-md-6">
  <div class="">
  <%= text_field_tag :search, params[:search], placeholder: "Where are you going?", class: "form-control",id:"pac-input" %>
</div>

</div>

<div class="col-md-6">
  <div id="map" style="height: 500px;">
      
  </div>
</div>
<script>
function initMap() {
  var map = new google.maps.Map(document.getElementById('map'), {
    center: {lat:<%= @latitude %>, lng: <%= @longitude %>},
    zoom: 13
  });
  var input = /** @type {!HTMLInputElement} */(
      document.getElementById('pac-input'));

  var autocomplete = new google.maps.places.Autocomplete(input);
  autocomplete.bindTo('bounds', map);
  
  // マーカーとインフォウィンドウの配列を用意
  markers = [];
  infowindows = [];

  <% @listings.each do |listing| %>
        
    //markerはこの関数の中で同じ変数
    var marker = new google.maps.Marker({
      position: new google.maps.LatLng(<%= listing.latitude %>, <%= listing.longitude %>),
      map: map
    });

    // マーカー配列にマーカを保存
    markers.push(marker);


  // var infowindow = new google.maps.InfoWindow();
  // var marker = new google.maps.Marker({
  //   map: map,
  //   anchorPoint: new google.maps.Point(0, -29)
  // });

  // autocomplete.addListener('place_changed', function() {
  //   infowindow.close();
  //   marker.setVisible(false);
  //   var place = autocomplete.getPlace();
  //   if (!place.geometry) {
  //     window.alert("Autocomplete's returned place contains no geometry");
  //     return;
  //   }

  //   // If the place has a geometry, then present it on a map.
  //   if (place.geometry.viewport) {
  //     map.fitBounds(place.geometry.viewport);
  //   } else {
  //     map.setCenter(place.geometry.location);
  //     map.setZoom(17);  // Why 17? Because it looks good.
  //   }
  //   marker.setIcon(/** @type {google.maps.Icon} */({
  //     url: place.icon,
  //     size: new google.maps.Size(71, 71),
  //     origin: new google.maps.Point(0, 0),
  //     anchor: new google.maps.Point(17, 34),
  //     scaledSize: new google.maps.Size(35, 35)
  //   }));
  //   marker.setPosition(place.geometry.location);
  //   marker.setVisible(true);

  //   infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + address);
  //   infowindow.open(map, marker);
  // });
}

</script>


    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA_cz1s18wSQrIRmZ7aAu9W4IpvzhKXaOc&libraries=places&callback=initMap"
        async defer></script>